sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t mapillary/mapillary_tools .

script:
  - docker run -w=/source/mapillary_tools/mapillary_tools mapillary/mapillary_tools /bin/sh -c "py.test"
